### 1.Model
MODEL:
  MODEL_NAME: "PSPNet"
  BACKBONE_NAME: "resnet50"
  INPUT_ROWS: 512
  INPUT_COLS: 512
  NUM_CLASSES: 3

### 2.Data
DATA:
  IMAGE_PATH: "./data/id_20190415/fg"
  LABEL_PATH: "./data/id_20190415/alpha"
  TRAIN_TXT_PATH: "./data/id_20190415/train_names.txt"
  VALID_TXT_PATH: "./data/id_20190415/valid_names.txt"
  TEST_TXT_PATH: "./data/id_20190415/test_names.txt"

### 3.Trainning 
TRAINNING:
  SPECIFIC_GPU_NUM: None
  INITIAL_LR: 0.01
  BATCH_SIZE: 4
  PATIENCE: 2
  EPOCHS: 200

### 4.Checkpoint
CHECKPOINT:
  MODEL_DIR_BASE: 'checkpoint'
  MODEL_DIR: 'PSPNet_20190428'
  TRAIN_PAIR_DIR: 'vis_train_pair'
  VALID_PAIR_DIR: 'vis_valid_pair'

### 5.Test
TEST:
  TEST_RESULT_PATH: './inference'
