### 1.Model
MODEL:
  MODEL_NAME: "PSPNet_temp"
  INPUT_ROWS: 512
  INPUT_COLS: 512
  RESNET_LAYERS: 50
  NUM_CLASSES: 3
  PT_PATH: "pspnet50_ade20k" 

### 2.Data
DATA:
  IMAGE_PATH: "./data/id_20190415/fg"
  LABEL_PATH: "./data/id_20190415/alpha"
  TRAIN_TXT_PATH: "./data/id_20190415/train_names.txt"
  VALID_TXT_PATH: "./data/id_20190415/valid_names.txt"
  TEST_TXT_PATH: "./data/id_20190415/test_names.txt"
  NUM_TRAIN: 3218       
  NUM_VALID: 402    

### 3.Trainning 
TRAINNING:
  SPECIFIC_GPU_NUM: None
  INITIAL_LR: 0.01
  BATCH_SIZE: 4
  PATIENCE: 2
  EPOCHS: 200

### 4.Checkpoint
CHECKPOINT:
  MODEL_DIR_BASE: 'checkpoint'
  MODEL_DIR: 'PSPNet_temp_20190415'
